from typing import Any

import yaml

from atlas.extract.result import ExtractResult

HEADER = (
    "# Generated by `atlas extract`. Do not edit — the next extraction run\n"
    "# overwrites this file in full. Corrections belong in data/relationships.yaml,\n"
    "# which survives extraction and wins every merge.\n"
)


def _dump(model: Any) -> dict[str, Any]:
    # mode="json" matters twice over: it turns StrEnum members into plain str
    # (yaml.safe_dump refuses to represent a str subclass) and it renders nested
    # Effect models as dicts. by_alias emits `from` rather than `from_`.
    return model.model_dump(mode="json", by_alias=True, exclude_none=True)


def _without_empty_lists(payload: dict[str, Any]) -> dict[str, Any]:
    return {k: v for k, v in payload.items() if v != []}


def to_yaml(result: ExtractResult) -> str:
    """Serialise an extraction to a loadable, byte-stable YAML document.

    Order follows the parsers, which walk their wikitext top to bottom, so the
    output is already deterministic without a sort. Re-sorting would be worse:
    `relic-10` sorts before `relic-2`, and the committed diff would stop
    tracking the wiki's own ordering.
    """
    nodes: dict[str, dict[str, Any]] = {}
    for node in result.nodes:
        nodes.setdefault(node.id, _without_empty_lists(_dump(node)))

    edges: dict[tuple[str, str, str, int | None], dict[str, Any]] = {}
    for edge in result.edges:
        key = (edge.from_, edge.to, str(edge.rel), edge.targets_effect)
        edges.setdefault(key, _dump(edge))

    doc = {"nodes": list(nodes.values()), "edges": list(edges.values())}
    body = yaml.safe_dump(
        doc,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        width=100,
    )
    return HEADER + "\n" + body
