import json
from typing import Any

import yaml

from atlas.extract.result import ExtractResult

HEADER = (
    "# Generated by `atlas extract`. Do not edit — the next extraction run\n"
    "# overwrites this file in full. Corrections belong in data/relationships.yaml,\n"
    "# which survives extraction and wins every merge.\n"
)


def _dump(model: Any) -> dict[str, Any]:
    # mode="json" is what converts StrEnum members to plain str, including the
    # ones nested inside Effect — yaml.safe_dump refuses to represent a str
    # subclass. (Nested models become dicts under mode="python" too, so that
    # part is not what this argument buys.) by_alias emits `from`, not `from_`.
    return model.model_dump(mode="json", by_alias=True, exclude_none=True)


def _without_empty_lists(payload: dict[str, Any]) -> dict[str, Any]:
    return {k: v for k, v in payload.items() if v != []}


def _identity(payload: dict[str, Any]) -> str:
    """A stable key standing for the whole payload.

    Keyed on every field rather than on the endpoints, because two edges that
    share `from`/`to`/`rel` are not necessarily the same claim: a card with two
    effects pointing at one target writes a distinct `note` for each, and
    dropping the second would delete evidence with nothing to report it.

    `json.dumps` rather than `tuple(sorted(payload.items()))` because a payload
    field may be a list or dict — `effects` already is on the node side — and a
    tuple of those is unhashable. mode="json" guarantees this cannot raise.
    """
    return json.dumps(payload, sort_keys=True, ensure_ascii=False)


def to_yaml(result: ExtractResult) -> str:
    """Serialise an extraction to a loadable, byte-stable YAML document.

    Order follows the parsers, which walk their wikitext top to bottom, so the
    output is already deterministic without a sort. Re-sorting would be worse:
    `relic-10` sorts before `relic-2`, and the committed diff would stop
    tracking the wiki's own ordering.
    """
    nodes: dict[str, dict[str, Any]] = {}
    for node in result.nodes:
        nodes.setdefault(node.id, _without_empty_lists(_dump(node)))

    edges: dict[str, dict[str, Any]] = {}
    for edge in result.edges:
        payload = _dump(edge)
        edges.setdefault(_identity(payload), payload)

    doc = {"nodes": list(nodes.values()), "edges": list(edges.values())}
    body = yaml.safe_dump(
        doc,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        width=100,
    )
    return HEADER + "\n" + body
