import yaml

from atlas.extract.emit import to_yaml
from atlas.extract.result import ExtractResult
from atlas.loader import load_dataset
from atlas.models import Edge, Effect, Kind, Node, Op, Rel


def _result() -> ExtractResult:
    return ExtractResult(
        nodes=[
            Node(
                id="relic-38",
                name="Smart Man",
                system="relics",
                kind=Kind.RELIC,
                wiki="Relics",
                effects=[
                    Effect(text="Adds base to Refine Node 2", per_level="+1.00", op=Op.ADD)
                ],
            ),
            Node(
                id="refine-node-2",
                name="Refine Node 2",
                system="refine-tree",
                kind=Kind.TREE_NODE,
                wiki="Minerals/Refine Tree",
            ),
        ],
        edges=[
            Edge(
                from_="relic-38",
                to="refine-node-2",
                rel=Rel.BOOSTS,
                op=Op.ADD,
                source="Relics",
            )
        ],
    )


def test_emitted_yaml_round_trips_through_the_loader(tmp_path):
    path = tmp_path / "derived.yaml"
    path.write_text(to_yaml(_result()), encoding="utf-8")

    ds = load_dataset(path)

    assert [n.id for n in ds.nodes] == ["relic-38", "refine-node-2"]
    assert ds.nodes[0].effects[0].per_level == "+1.00"
    assert ds.nodes[0].effects[0].op is Op.ADD
    assert ds.edges[0].from_ == "relic-38"
    assert ds.edges[0].rel is Rel.BOOSTS


def test_emitted_yaml_uses_the_from_alias_not_the_python_field_name():
    # `from` is a Python keyword, so the model calls the attribute `from_`.
    # Emitting `from_:` would produce a file the loader rejects.
    doc = yaml.safe_load(to_yaml(_result()))
    assert "from" in doc["edges"][0]
    assert "from_" not in doc["edges"][0]


def test_emitted_yaml_omits_unset_optional_fields():
    doc = yaml.safe_load(to_yaml(_result()))
    assert "note" not in doc["edges"][0]
    assert "targets_effect" not in doc["edges"][0]
    # An empty effects list is noise on 136 refine nodes.
    assert "effects" not in doc["nodes"][1]


def test_emitted_yaml_carries_a_do_not_edit_header():
    text = to_yaml(_result())
    assert text.startswith("# Generated by `atlas extract`")
    assert "data/relationships.yaml" in text.splitlines()[1]


def test_emit_is_byte_stable_and_drops_duplicates():
    result = _result()
    result.nodes.append(result.nodes[0].model_copy())
    result.edges.append(result.edges[0].model_copy())

    text = to_yaml(result)
    assert text == to_yaml(result)

    doc = yaml.safe_load(text)
    assert [n["id"] for n in doc["nodes"]] == ["relic-38", "refine-node-2"]
    assert len(doc["edges"]) == 1
