from dataclasses import dataclass, field
from pathlib import Path

import networkx as nx
import yaml

from atlas.models import Dataset, NodeConfidence


@dataclass
class CoverageReport:
    orphans: list[str] = field(default_factory=list)
    cycles: list[list[str]] = field(default_factory=list)
    per_system: dict[str, tuple[int, int]] = field(default_factory=dict)
    stub_count: int = 0
    node_count: int = 0
    edge_count: int = 0
    missing_entities: dict[str, list[str]] = field(default_factory=dict)
    has_inventory: bool = False


def load_inventory(path: Path) -> dict[str, list[str]] | None:
    """Read the optional IL2CPP entity inventory. None when the file is absent."""
    if not path.is_file():
        return None
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def _build_graph(ds: Dataset) -> nx.DiGraph:
    graph = nx.DiGraph()
    graph.add_nodes_from(n.id for n in ds.nodes)
    known = ds.node_ids()
    for edge in ds.edges:
        if edge.from_ in known and edge.to in known:
            graph.add_edge(edge.from_, edge.to)
    return graph


def analyse(
    ds: Dataset, inventory: dict[str, list[str]] | None = None
) -> CoverageReport:
    graph = _build_graph(ds)

    orphans = sorted(n for n in graph.nodes if graph.degree(n) == 0)

    cycles = sorted(
        (sorted(component) for component in nx.strongly_connected_components(graph)
         if len(component) > 1),
        key=lambda component: (-len(component), component[0]),
    )

    per_system: dict[str, tuple[int, int]] = {}
    for node in ds.nodes:
        connected, total = per_system.get(node.system, (0, 0))
        is_connected = graph.degree(node.id) > 0
        per_system[node.system] = (connected + int(is_connected), total + 1)

    stub_count = sum(
        1 for n in ds.nodes if n.confidence is NodeConfidence.UNKNOWN
    )

    known = ds.node_ids()
    missing_entities = {}
    for system, entity_ids in (inventory or {}).items():
        absent = sorted(e for e in entity_ids if e not in known)
        if absent:
            missing_entities[system] = absent

    return CoverageReport(
        orphans=orphans,
        cycles=cycles,
        per_system=per_system,
        stub_count=stub_count,
        node_count=len(ds.nodes),
        edge_count=len(ds.edges),
        missing_entities=missing_entities,
        has_inventory=inventory is not None,
    )


def render_markdown(report: CoverageReport) -> str:
    lines = [
        "# Coverage report",
        "",
        "Generated by `atlas build`. Do not edit by hand.",
        "",
        f"- Nodes: {report.node_count}",
        f"- Edges: {report.edge_count}",
        f"- Stubs (confidence `unknown`): {report.stub_count}",
        "",
        "## Per-system coverage",
        "",
        "| System | Connected | Total | Coverage |",
        "|---|---|---|---|",
    ]
    for system in sorted(report.per_system):
        connected, total = report.per_system[system]
        pct = (100 * connected // total) if total else 0
        lines.append(f"| {system} | {connected} | {total} | {pct}% |")

    lines += ["", "## Orphan nodes", ""]
    if report.orphans:
        lines.append("Nodes with no edges in either direction — the curation to-do list.")
        lines.append("")
        lines += [f"- `{node_id}`" for node_id in report.orphans]
    else:
        lines.append("None.")

    lines += ["", "## Feedback loops", ""]
    if report.cycles:
        lines.append("Strongly connected components. These are real game mechanics, not errors.")
        lines.append("")
        for component in report.cycles:
            lines.append("- " + " → ".join(f"`{n}`" for n in component))
    else:
        lines.append("None.")

    if report.has_inventory:
        lines += ["", "## Known unknowns", ""]
        if report.missing_entities:
            lines.append(
                "Entities the game's enums prove exist but which have no node yet."
            )
            lines.append("")
            for system in sorted(report.missing_entities):
                lines.append(f"### {system}")
                lines.append("")
                lines += [f"- `{e}`" for e in report.missing_entities[system]]
                lines.append("")
            lines.pop()
        else:
            lines.append("None — every inventoried entity has a node.")

    return "\n".join(lines) + "\n"
